### ISSUE TITLE
Suggestions for benchmarks/get_installation.sh

### ISSUE THREAD

**Issue by holgersson32644** [HyVar/gentoo_to_mspl#1]
Hi, I read you email on the gentoo-dev ML and took a look at your script. The following two
things came to my mind (beside the one that was mentioned there):
- check for configurations in directories aswell. I couldn't find anything about it in the PMS, but portage
supports directories inside /etc/portage atleast for far over a year that I can remember of that
- create a tarball with a proper name, i.e. ending with .tar.xz. XZ can be somewhat annyoing about the file name, and it makes the detection of the generated tarball just easier for other testers.

The first one can be solved (pun not intended) with find, but maybe you find a prettier solution.

**Comment by gzoumix** [comment]
Thanks for the suggestions :).
 - I am aware that /etc/portage/package.* can be directories, and the default behavior of tar is to include the full folder tree when the argument is a folder (man tar). I tested to be sure, there is no problem with the script on that end
 - you are right about the archive name. I changed it to installation_spec.tar.xz
